# yaml 配置
version: '1.0.3-dev'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    links:
      - mongo
    environment:
      - MONGO_URL=mongodb://root:example@mongo:27017
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
